name: Plumbline Ireland
favicon: null
layout_spectrum: 0.1931
typography_spectrum: 0.9911295992787927
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9168852563016117
  lightness: 0.2439945845399052
  saturation: 0.6490581799298525
  rhythmicContrast: 0.11942771053873003
purpose: []
