name: Plumbline Ireland
favicon: null
layout_spectrum: 0.1931
typography_spectrum: 0.38412
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#123673'
    - '#295fa1'
    - '#74abcd'
    - '#c0e4ec'
  brandStrength: 0.5625
  lightness: 0.2439945845399052
  saturation: 0.6490581799298525
  rhythmicContrast: 0.11942771053873003
purpose: []
